package test

import (
	"github.com/rs/zerolog/log"
	"io"
	"keycloak-user-service/types"
	"net/http"
)

func AddAuthorizationHeader(req *http.Request) *http.Request {
	testToken := `eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBWHNqSlFmbkMtdlRWVGpiSFViRTl1VS1mZUZPWnBEZVgwcUxnbWJlY0xZIn0.eyJleHAiOjE2ODM4MDg5NDcsImlhdCI6MTY4MzgwODg4NywianRpIjoiNTk3MmEyMWYtOWFhYy00M2M5LWI3MmMtYWIwZDgyZTE2YmVjIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9tYXN0ZXIiLCJzdWIiOiIxODE1NGJhNi0wYTY2LTQxNGQtODNjOS04YzYwZGZmNGMxYWQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhZG1pbi1jbGkiLCJzZXNzaW9uX3N0YXRlIjoiMzBkZTUyNzQtODhhYS00MmNmLWJlZWQtMDM1NmUwMjc3MGJlIiwiYWNyIjoiMSIsInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6IjMwZGU1Mjc0LTg4YWEtNDJjZi1iZWVkLTAzNTZlMDI3NzBiZSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW4ifQ.J6P7-myYtYEjiVW-IWH-euOkWJP11N8tRs-Fs89pyAB0xHOLNMQpIRQ1mUW6Cr_axqZo5Z8AyXiWF-IQnHRzO8aWg6B2XwyzDgc887RXa__qrLXOZK0OUfc9T_O_t0VI7_y593E0KPkTodSi9M_7W2txE3XaQ0n1EvoTSINM9ZasLe20S5ij7ZTbMVER0g8P9AJxWOD6LU5xdWIF068WpVzGEvEKD2oHlBbcy8fdH_uavWloHoXXbb-jpJAxzYU3VsNIOLJYXXolkSAvkUOFXEuirvA764uYjCYOj0MIq4VWvPYVzEjt1BDELzLRYnd3UvwnTBFcVm4sh8cY89hOKg`
	req.Header.Add(types.AUTHORIZATION_HEADER, "Bearer "+testToken)
	log.Debug().Msg("ADDING ACCESS_TOKEN: " + req.Header.Get(types.AUTHORIZATION_HEADER))
	return req
}

func GetNewHttpRequest(method string, url string, body io.Reader) *http.Request {
	req, _ := http.NewRequest(method, url, body)
	req = AddAuthorizationHeader(req)
	return req
}
